version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - mongodb
    networks:
      - bot_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  mongodb_data:
